### ISSUE TITLE
Tab Styling Presets and Customization

### ISSUE THREAD

**Issue by ashberg** [eecs-autograder/ag-website-vue#26]
Currently the styles for the tabs are in the styles folder in the file 'tab_styles.scss.' The tabs must be styled a certain way when the body of the tab has a border-top applied, and differently when it is not applied. I'm not sure where the presence of a border-top on the body should be specified, (As a boolean prop in the tabs component? As a style applied to a preset that the user just indicates via the active and inactive class props for tabs? etc.) Should a component be able to specify a color for the tabs that is not included in the presets or should all styles reside in tab_styles.scss?

**Comment by james-perretta** [comment]
Good enough for now
