### ISSUE TITLE
Right-justify delete buttons in ag suites and mutation suites editing

### ISSUE THREAD

**Issue by james-perretta** [eecs-autograder/ag-website-vue#286]
It's easy to scroll all the way down for the save button and accidentally click the delete button. Right-justifying the delete button will help.

**Comment by james-perretta** [comment]
See also #285

**Comment by jajanet** [comment]
Hi James! I'm Ben's partner for our class open-source contribution project. I'm currently looking at this issue and made a mock of what could be a good solution based on what you sent to Ben. Let me know what you think, and I'll be happy to iterate some code and designs to your standards :)
![delete-mock](https://user-images.githubusercontent.com/31081135/69597483-223b0c80-0fd4-11ea-8820-716c04a9a6b2.png)
Initial mock of a potential solution

![del-mock-close](https://user-images.githubusercontent.com/31081135/69597587-70501000-0fd4-11ea-9056-56147097ca43.png)
A closer view of the mock

![delete-github-example](https://user-images.githubusercontent.com/31081135/69597484-223b0c80-0fd4-11ea-8051-808f3661c27c.png)
Github's solution for danger zone styling, which the solution is based off of

**Comment by james-perretta** [comment]
Hi Janet, thanks for taking on this issue!

I think that putting a border around it and having a label opposite the button both help. However, those things make me less certain about the text that currently says "Danger Zone." 

With the text positioned as in your mockup, I think something along the lines of `Delete` or `Delete "<test suite name>"` makes a bit more sense. What to you think?

**Comment by jajanet** [comment]
Yeah, sure! I agree replacing danger zone makes sense since there's only one action. What do you think about this mock?
![del-mock-close](https://user-images.githubusercontent.com/31081135/69659418-23a81b80-104c-11ea-8ac5-18c3e174388b.png)

**Comment by jajanet** [comment]
Here's a small variation on the above mock:
![del-mock-close](https://user-images.githubusercontent.com/31081135/69661370-44727000-1050-11ea-9429-885a449290b3.png)

**Comment by james-perretta** [comment]
I like the one that I marked with :+1: 
A couple of other thoughts:
- I'd put a healthy amount of space between the "last modified" timestamp and the delete box
- Make sure that the text wraps decently if the suite name is long (set word-break: break-word; and word-wrap: break-word;) and/or the screen size is down to about 500px

With those things in mind, I think you can go ahead and implement this for real!
