### ISSUE TITLE
Re-style closing x for modal

### ISSUE THREAD

**Issue by james-perretta** [eecs-autograder/ag-website-vue#307]

**Comment by jajanet** [comment]
Hey James! What do you think about using a traditional 'X' style for the modal? On hover, I was thinking of making the color of 'X' lighter. This is a pretty generic solution that would be a good starting point for styling, and would be happy to adjust to what works best for you!

Here's a couple examples:
![modal-x-mock](https://user-images.githubusercontent.com/31081135/69659451-37ec1880-104c-11ea-943a-f71bc17e6701.png)
View of the X
![modal-x-mock-close](https://user-images.githubusercontent.com/31081135/69659450-37ec1880-104c-11ea-93b6-71dfae5433f7.png)
Closer view

**Comment by james-perretta** [comment]
Hi Janet, My apologies, but I already have a fix for this staged on another branch I'm working on. Ben mentioned #306 in his email but not this one, so I didn't realize you wanted to work on this as well. If you need another issue, I'm happy to suggest one over email.

**Comment by jajanet** [comment]
My apologies, Ben and I made a 1-off error (I was supposed to look at #306 instead) while working on issues. Thanks for clearing that up, and sorry for any confusion!
