### ISSUE TITLE
differently-sized "+" characters in Test Cases vs. Mutation Testing

### ISSUE THREAD

**Issue by hoosierEE** [eecs-autograder/ag-website-vue#388]
Not a big deal, but just wanted to let you know the plus icons are different sizes:

<img width="513" alt="Screen Shot 2020-01-20 at 9 57 39 AM" src="https://user-images.githubusercontent.com/4307625/72736247-5dd4fb80-3b6b-11ea-9516-8e80dd8ae700.png">
<img width="486" alt="Screen Shot 2020-01-20 at 9 57 49 AM" src="https://user-images.githubusercontent.com/4307625/72736257-5f062880-3b6b-11ea-96d8-aaec56e1561d.png">

**Comment by james-perretta** [comment]
Fixed along with PR #418
